/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageAI from "../../../../api/index";
import * as core from "../../../../core";

export const ContextualizedembeddingsApiRequestOutputDtype: core.serialization.Schema<
    serializers.ContextualizedembeddingsApiRequestOutputDtype.Raw,
    VoyageAI.ContextualizedembeddingsApiRequestOutputDtype
> = core.serialization.enum_(["float", "int8", "uint8", "binary", "ubinary"]);

export declare namespace ContextualizedembeddingsApiRequestOutputDtype {
    type Raw = "float" | "int8" | "uint8" | "binary" | "ubinary";
}
