/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageAI from "../../../../api/index";
import * as core from "../../../../core";
import { ContextualizedembeddingsApiResponseResultsItemEmbeddingsItem } from "./ContextualizedembeddingsApiResponseResultsItemEmbeddingsItem";

export const ContextualizedembeddingsApiResponseResultsItem: core.serialization.ObjectSchema<
    serializers.ContextualizedembeddingsApiResponseResultsItem.Raw,
    VoyageAI.ContextualizedembeddingsApiResponseResultsItem
> = core.serialization.object({
    embeddings: core.serialization.list(ContextualizedembeddingsApiResponseResultsItemEmbeddingsItem).optional(),
    documentIndex: core.serialization.property("document_index", core.serialization.number().optional()),
});

export declare namespace ContextualizedembeddingsApiResponseResultsItem {
    interface Raw {
        embeddings?: ContextualizedembeddingsApiResponseResultsItemEmbeddingsItem.Raw[] | null;
        document_index?: number | null;
    }
}
