/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageAI from "../../../../api/index";
import * as core from "../../../../core";

export const ContextualizedembeddingsApiRequestInputType: core.serialization.Schema<
    serializers.ContextualizedembeddingsApiRequestInputType.Raw,
    VoyageAI.ContextualizedembeddingsApiRequestInputType
> = core.serialization.enum_(["query", "document"]);

export declare namespace ContextualizedembeddingsApiRequestInputType {
    type Raw = "query" | "document";
}
