/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageAI from "../../../../api/index";
import * as core from "../../../../core";

export const ContextualizedembeddingsApiResponseResultsItemEmbeddingsItem: core.serialization.ObjectSchema<
    serializers.ContextualizedembeddingsApiResponseResultsItemEmbeddingsItem.Raw,
    VoyageAI.ContextualizedembeddingsApiResponseResultsItemEmbeddingsItem
> = core.serialization.object({
    object: core.serialization.string().optional(),
    embedding: core.serialization.list(core.serialization.number()).optional(),
    index: core.serialization.number().optional(),
});

export declare namespace ContextualizedembeddingsApiResponseResultsItemEmbeddingsItem {
    interface Raw {
        object?: string | null;
        embedding?: number[] | null;
        index?: number | null;
    }
}
