/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageAI from "../../../../api/index";
import * as core from "../../../../core";

export const ContextualizedembeddingsApiResponseUsage: core.serialization.ObjectSchema<
    serializers.ContextualizedembeddingsApiResponseUsage.Raw,
    VoyageAI.ContextualizedembeddingsApiResponseUsage
> = core.serialization.object({
    totalTokens: core.serialization.property("total_tokens", core.serialization.number().optional()),
});

export declare namespace ContextualizedembeddingsApiResponseUsage {
    interface Raw {
        total_tokens?: number | null;
    }
}
