/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageApi from "../../../../api/index";
import * as core from "../../../../core";

export const EmbeddingsApiRequestInput: core.serialization.Schema<
    serializers.EmbeddingsApiRequestInput.Raw,
    VoyageApi.EmbeddingsApiRequestInput
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace EmbeddingsApiRequestInput {
    type Raw = string | string[];
}
