/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageApi from "../../../../api/index";
import * as core from "../../../../core";
import { EmbeddingsApiResponseDataItem } from "./EmbeddingsApiResponseDataItem";
import { EmbeddingsApiResponseUsage } from "./EmbeddingsApiResponseUsage";

export const EmbeddingsApiResponse: core.serialization.ObjectSchema<
    serializers.EmbeddingsApiResponse.Raw,
    VoyageApi.EmbeddingsApiResponse
> = core.serialization.object({
    object: core.serialization.string().optional(),
    data: core.serialization.list(EmbeddingsApiResponseDataItem).optional(),
    model: core.serialization.string().optional(),
    usage: EmbeddingsApiResponseUsage.optional(),
});

export declare namespace EmbeddingsApiResponse {
    interface Raw {
        object?: string | null;
        data?: EmbeddingsApiResponseDataItem.Raw[] | null;
        model?: string | null;
        usage?: EmbeddingsApiResponseUsage.Raw | null;
    }
}
