/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageApi from "../../../../api/index";
import * as core from "../../../../core";

export const EmbeddingsApiResponseDataItem: core.serialization.ObjectSchema<
    serializers.EmbeddingsApiResponseDataItem.Raw,
    VoyageApi.EmbeddingsApiResponseDataItem
> = core.serialization.object({
    object: core.serialization.string().optional(),
    embedding: core.serialization.list(core.serialization.number()).optional(),
    index: core.serialization.number().optional(),
});

export declare namespace EmbeddingsApiResponseDataItem {
    interface Raw {
        object?: string | null;
        embedding?: number[] | null;
        index?: number | null;
    }
}
