/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageApi from "../../../../api/index";
import * as core from "../../../../core";

export const EmbeddingsApiRequestInputType: core.serialization.Schema<
    serializers.EmbeddingsApiRequestInputType.Raw,
    VoyageApi.EmbeddingsApiRequestInputType
> = core.serialization.enum_(["query", "document"]);

export declare namespace EmbeddingsApiRequestInputType {
    type Raw = "query" | "document";
}
