/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageAI from "../../../../api/index";
import * as core from "../../../../core";

export const MultimodalembeddingsApiRequestInputsItem: core.serialization.ObjectSchema<
    serializers.MultimodalembeddingsApiRequestInputsItem.Raw,
    VoyageAI.MultimodalembeddingsApiRequestInputsItem
> = core.serialization.object({
    content: core.serialization.unknown().optional(),
});

export declare namespace MultimodalembeddingsApiRequestInputsItem {
    interface Raw {
        content?: unknown | null;
    }
}
