/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageAI from "../../../../api/index";
import * as core from "../../../../core";

export const MultimodalembeddingsApiRequestInputType: core.serialization.Schema<
    serializers.MultimodalembeddingsApiRequestInputType.Raw,
    VoyageAI.MultimodalembeddingsApiRequestInputType
> = core.serialization.enum_(["query", "document"]);

export declare namespace MultimodalembeddingsApiRequestInputType {
    type Raw = "query" | "document";
}
