/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as VoyageApi from "../../../../api/index";
import * as core from "../../../../core";
import { RerankerApiResponseDataItem } from "./RerankerApiResponseDataItem";
import { RerankerApiResponseUsage } from "./RerankerApiResponseUsage";

export const RerankerApiResponse: core.serialization.ObjectSchema<
    serializers.RerankerApiResponse.Raw,
    VoyageApi.RerankerApiResponse
> = core.serialization.object({
    object: core.serialization.string().optional(),
    data: core.serialization.list(RerankerApiResponseDataItem).optional(),
    model: core.serialization.string().optional(),
    usage: RerankerApiResponseUsage.optional(),
});

export declare namespace RerankerApiResponse {
    interface Raw {
        object?: string | null;
        data?: RerankerApiResponseDataItem.Raw[] | null;
        model?: string | null;
        usage?: RerankerApiResponseUsage.Raw | null;
    }
}
