/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class VoyageAITimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, VoyageAITimeoutError.prototype);
    }
}
