/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class VoyageApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, VoyageApiTimeoutError.prototype);
    }
}
