// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../../api/index.js";
import * as core from "../../../core/index.js";
import type * as serializers from "../../index.js";
import { ContextualizedEmbedRequestInputType } from "../../types/ContextualizedEmbedRequestInputType.js";
import { ContextualizedEmbedRequestOutputDtype } from "../../types/ContextualizedEmbedRequestOutputDtype.js";

export const ContextualizedEmbedRequest: core.serialization.Schema<
    serializers.ContextualizedEmbedRequest.Raw,
    VoyageAI.ContextualizedEmbedRequest
> = core.serialization.object({
    inputs: core.serialization.list(core.serialization.list(core.serialization.string())),
    model: core.serialization.string(),
    inputType: core.serialization.property("input_type", ContextualizedEmbedRequestInputType.optional()),
    outputDimension: core.serialization.property("output_dimension", core.serialization.number().optional()),
    outputDtype: core.serialization.property("output_dtype", ContextualizedEmbedRequestOutputDtype.optional()),
});

export declare namespace ContextualizedEmbedRequest {
    export interface Raw {
        inputs: string[][];
        model: string;
        input_type?: ContextualizedEmbedRequestInputType.Raw | null;
        output_dimension?: number | null;
        output_dtype?: ContextualizedEmbedRequestOutputDtype.Raw | null;
    }
}
