// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../../api/index.js";
import * as core from "../../../core/index.js";
import type * as serializers from "../../index.js";
import { EmbedRequestEncodingFormat } from "../../types/EmbedRequestEncodingFormat.js";
import { EmbedRequestInput } from "../../types/EmbedRequestInput.js";
import { EmbedRequestInputType } from "../../types/EmbedRequestInputType.js";
import { EmbedRequestOutputDtype } from "../../types/EmbedRequestOutputDtype.js";

export const EmbedRequest: core.serialization.Schema<serializers.EmbedRequest.Raw, VoyageAI.EmbedRequest> =
    core.serialization.object({
        input: EmbedRequestInput,
        model: core.serialization.string(),
        inputType: core.serialization.property("input_type", EmbedRequestInputType.optional()),
        truncation: core.serialization.boolean().optional(),
        encodingFormat: core.serialization.property("encoding_format", EmbedRequestEncodingFormat.optional()),
        outputDimension: core.serialization.property("output_dimension", core.serialization.number().optional()),
        outputDtype: core.serialization.property("output_dtype", EmbedRequestOutputDtype.optional()),
    });

export declare namespace EmbedRequest {
    export interface Raw {
        input: EmbedRequestInput.Raw;
        model: string;
        input_type?: EmbedRequestInputType.Raw | null;
        truncation?: boolean | null;
        encoding_format?: EmbedRequestEncodingFormat.Raw | null;
        output_dimension?: number | null;
        output_dtype?: EmbedRequestOutputDtype.Raw | null;
    }
}
