/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as VoyageAI from "../../../api/index";
import * as core from "../../../core";
import { EmbedRequestInput } from "../../types/EmbedRequestInput";
import { EmbedRequestInputType } from "../../types/EmbedRequestInputType";
import { EmbedRequestOutputDtype } from "../../types/EmbedRequestOutputDtype";

export const EmbedRequest: core.serialization.Schema<serializers.EmbedRequest.Raw, VoyageAI.EmbedRequest> =
    core.serialization.object({
        input: EmbedRequestInput,
        model: core.serialization.string(),
        inputType: core.serialization.property("input_type", EmbedRequestInputType.optional()),
        truncation: core.serialization.boolean().optional(),
        encodingFormat: core.serialization.property(
            "encoding_format",
            core.serialization.stringLiteral("base64").optional()
        ),
        outputDimension: core.serialization.property("output_dimension", core.serialization.number().optional()),
        outputDtype: core.serialization.property("output_dtype", EmbedRequestOutputDtype.optional()),
    });

export declare namespace EmbedRequest {
    interface Raw {
        input: EmbedRequestInput.Raw;
        model: string;
        input_type?: EmbedRequestInputType.Raw | null;
        truncation?: boolean | null;
        encoding_format?: "base64" | null;
        output_dimension?: number | null;
        output_dtype?: EmbedRequestOutputDtype.Raw | null;
    }
}
