/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as VoyageAI from "../../../api/index";
import * as core from "../../../core";
import { MultimodalEmbedRequestInputsItem } from "../../types/MultimodalEmbedRequestInputsItem";
import { MultimodalEmbedRequestInputType } from "../../types/MultimodalEmbedRequestInputType";

export const MultimodalEmbedRequest: core.serialization.Schema<
    serializers.MultimodalEmbedRequest.Raw,
    VoyageAI.MultimodalEmbedRequest
> = core.serialization.object({
    inputs: core.serialization.list(MultimodalEmbedRequestInputsItem),
    model: core.serialization.string(),
    inputType: core.serialization.property("input_type", MultimodalEmbedRequestInputType.optional()),
    truncation: core.serialization.boolean().optional(),
    encodingFormat: core.serialization.property(
        "encoding_format",
        core.serialization.stringLiteral("base64").optional()
    ),
});

export declare namespace MultimodalEmbedRequest {
    interface Raw {
        inputs: MultimodalEmbedRequestInputsItem.Raw[];
        model: string;
        input_type?: MultimodalEmbedRequestInputType.Raw | null;
        truncation?: boolean | null;
        encoding_format?: "base64" | null;
    }
}
