// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../../api/index.js";
import * as core from "../../../core/index.js";
import type * as serializers from "../../index.js";
import { MultimodalEmbedRequestEncodingFormat } from "../../types/MultimodalEmbedRequestEncodingFormat.js";
import { MultimodalEmbedRequestInputsItem } from "../../types/MultimodalEmbedRequestInputsItem.js";
import { MultimodalEmbedRequestInputType } from "../../types/MultimodalEmbedRequestInputType.js";

export const MultimodalEmbedRequest: core.serialization.Schema<
    serializers.MultimodalEmbedRequest.Raw,
    VoyageAI.MultimodalEmbedRequest
> = core.serialization.object({
    inputs: core.serialization.list(MultimodalEmbedRequestInputsItem),
    model: core.serialization.string(),
    inputType: core.serialization.property("input_type", MultimodalEmbedRequestInputType.optional()),
    truncation: core.serialization.boolean().optional(),
    encodingFormat: core.serialization.property("encoding_format", MultimodalEmbedRequestEncodingFormat.optional()),
});

export declare namespace MultimodalEmbedRequest {
    export interface Raw {
        inputs: MultimodalEmbedRequestInputsItem.Raw[];
        model: string;
        input_type?: MultimodalEmbedRequestInputType.Raw | null;
        truncation?: boolean | null;
        encoding_format?: MultimodalEmbedRequestEncodingFormat.Raw | null;
    }
}
