/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as VoyageAI from "../../../index";

export interface ContextualizedembeddingsApiResponse {
    /** The object type, which is always "contextualized_embeddings". */
    object?: string;
    /** An array of contextualized embedding results, one for each input document. */
    results?: VoyageAI.ContextualizedembeddingsApiResponseResultsItem[];
    /** Name of the model used. */
    model?: string;
    usage?: VoyageAI.ContextualizedembeddingsApiResponseUsage;
}
