/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ContextualizedembeddingsApiResponseUsage {
    /** The total number of tokens used for computing the contextualized embeddings. */
    totalTokens?: number;
}
