/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as VoyageAI from "../../../index";

export interface ContextualizedembeddingsApiResponseResultsItem {
    /** An array of embeddings for each chunk in the document. */
    embeddings?: VoyageAI.ContextualizedembeddingsApiResponseResultsItemEmbeddingsItem[];
    /** The index of this document within the input list. */
    documentIndex?: number;
}
