/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EmbeddingsApiResponseUsage {
    /** The total number of tokens used for computing the embeddings. */
    totalTokens?: number;
}
