/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as VoyageAI from "../../../index";

export interface MultimodalembeddingsApiResponse {
    /** The object type, which is always "list". */
    object?: string;
    /** An array of embedding objects. */
    data?: VoyageAI.MultimodalembeddingsApiResponseDataItem[];
    /** Name of the model. */
    model?: string;
    usage?: VoyageAI.MultimodalembeddingsApiResponseUsage;
}
