/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as VoyageApi from "../../../index";

export interface RerankerApiResponse {
    /** The object type, which is always "list". */
    object?: string;
    /** An array of the reranking results, sorted by the descending order of relevance scores. */
    data?: VoyageApi.RerankerApiResponseDataItem[];
    /** Name of the model. */
    model?: string;
    usage?: VoyageApi.RerankerApiResponseUsage;
}
