// This file was auto-generated by Fern from our API Definition.

export interface ContextualizedEmbedResponseDataItemDataItem {
    /** The object type, which is always "embedding". */
    object?: string;
    /** The contextualized embedding vector for this chunk, represented as an array of numbers. The data type depends on the `output_dtype` parameter: floating-point numbers for `float`, integers for `int8`, `uint8`, `binary`, and `ubinary`. */
    embedding?: number[];
    /** The index of this chunk within the document. */
    index?: number;
}
