// This file was auto-generated by Fern from our API Definition.

/**
 * A list of documents, where each document is represented as a list of text chunks (strings). When `enable_auto_chunking` is `true` or `input_type` is `query`, inputs can also be a flat list of strings (one string per document or query). <ul> <li> The maximum number of inputs (documents) is 1,000. </li> <li> The total number of chunks across all documents cannot exceed 16,000. </li> <li> The total number of tokens across all inputs cannot exceed 120,000. </li> </ul>
 */
export type ContextualizedEmbedRequestInputs =
    /**
     * A list of documents, each represented as a list of text chunks. */
    | string[][]
    /**
     * A flat list of strings (one per document or query). Use with `enable_auto_chunking` or `input_type` set to `query`. */
    | string[];
