// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../index.js";

export interface ContextualizedEmbedResponseDataItem {
    /** The object type, which is always "list". */
    object?: string;
    /** An array of embeddings for each chunk in the document. */
    data?: VoyageAI.ContextualizedEmbedResponseDataItemDataItem[];
    /** The index of this document within the input list. */
    index?: number;
}
