/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as VoyageAI from "../index";

export interface ContextualizedEmbedResponse {
    /** The object type, which is always "contextualized_embeddings". */
    object?: string;
    /** An array of contextualized embedding results, one for each input document. */
    data?: VoyageAI.ContextualizedEmbedResponseDataItem[];
    /** Name of the model used. */
    model?: string;
    usage?: VoyageAI.ContextualizedEmbedResponseUsage;
}
