/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The data type for the embeddings to be returned. Defaults to `float`.  Other options: `int8`, `uint8`, `binary`, `ubinary`. `float` is supported for all models.  `int8`, `uint8`, `binary`, and `ubinary` are supported by `voyage-3-large` and `voyage-code-3`.  Please see our guide for more details about output data types.
 */
export type EmbedRequestOutputDtype = "float" | "int8" | "uint8" | "binary" | "ubinary";

export const EmbedRequestOutputDtype = {
    Float: "float",
    Int8: "int8",
    Uint8: "uint8",
    Binary: "binary",
    Ubinary: "ubinary",
} as const;
