/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the input text. Defaults to `null`. Other options: `query`, `document`.
 */
export type EmbedRequestInputType = "query" | "document";

export const EmbedRequestInputType = {
    Query: "query",
    Document: "document",
} as const;
