/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EmbedResponse {
    /** The object type, which is always "list". */
    object?: string;
    /** An array of embedding objects. */
    data?: EmbedResponse.Data.Item[];
    /** Name of the model. */
    model?: string;
    usage?: EmbedResponse.Usage;
}

export namespace EmbedResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** The object type, which is always "embedding". */
            object?: string;
            /** Each embedding is a vector represented as an array of `float` numbers when `output_dtype` is set to `float`  and as an array of integers for all other values of `output_dtype` (`int8`, `uint8`, `binary`, and `ubinary`).  The length of this vector varies depending on the specific model, `output_dimension`, and `output_dtype`. */
            embedding?: number[];
            /** An integer representing the index of the embedding within the list of embeddings. */
            index?: number;
        }
    }

    export interface Usage {
        /** The total number of tokens used for computing the embeddings. */
        total_tokens?: number;
    }
}
