/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as VoyageApi from "../index";

export interface EmbedResponse {
    /** The object type, which is always "list". */
    object?: string;
    /** An array of embedding objects. */
    data?: VoyageApi.EmbedResponseDataItem[];
    /** Name of the model. */
    model?: string;
    usage?: VoyageApi.EmbedResponseUsage;
}
