/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MultimodalEmbedResponse {
    /** The object type, which is always "list". */
    object?: string;
    /** An array of embedding objects. */
    data?: MultimodalEmbedResponse.Data.Item[];
    /** Name of the model. */
    model?: string;
    usage?: MultimodalEmbedResponse.Usage;
}

export namespace MultimodalEmbedResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** The object type, which is always "embedding". */
            object?: string;
            /** The embedding vector consists of a list of floating-point numbers. The length of this vector varies depending on the specific model. */
            embedding?: number[];
            /** An integer representing the index of the embedding within the list of embeddings. */
            index?: number;
        }
    }

    export interface Usage {
        /** The total number of tokens used for computing the embeddings. */
        total_tokens?: number;
    }
}
