// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../index.js";

export interface MultimodalEmbedResponse {
    /** The object type, which is always "list". */
    object?: string;
    /** An array of embedding objects. */
    data?: VoyageAI.MultimodalEmbedResponseDataItem[];
    /** Name of the model. */
    model?: string;
    usage?: VoyageAI.MultimodalEmbedResponseUsage;
}
