// This file was auto-generated by Fern from our API Definition.

/** Format in which the embeddings are encoded. We support two options:  <ul> <li> If not specified (defaults to `null`): the embeddings are represented as lists of floating-point numbers; </li>  <li> `base64`: the embeddings are compressed to [base64](https://docs.python.org/3/library/base64.html) encodings. </li>  </ul> */
export const MultimodalEmbedRequestEncodingFormat = {
    Base64: "base64",
} as const;
export type MultimodalEmbedRequestEncodingFormat =
    (typeof MultimodalEmbedRequestEncodingFormat)[keyof typeof MultimodalEmbedRequestEncodingFormat];
