/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RerankResponse {
    /** The object type, which is always "list". */
    object?: string;
    /** An array of the reranking results, sorted by the descending order of relevance scores. */
    data?: RerankResponse.Data.Item[];
    /** Name of the model. */
    model?: string;
    usage?: RerankResponse.Usage;
}

export namespace RerankResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            /** The index of the document in the input list. */
            index?: number;
            /** The relevance score of the document with respect to the query. */
            relevance_score?: number;
            /** The document string. Only returned when return_documents is set to true. */
            document?: string;
        }
    }

    export interface Usage {
        /** The total number of tokens used for computing the reranking. */
        total_tokens?: number;
    }
}
