// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ContextualizedEmbedResponseDataItem } from "./ContextualizedEmbedResponseDataItem.js";
import { ContextualizedEmbedResponseUsage } from "./ContextualizedEmbedResponseUsage.js";

export const ContextualizedEmbedResponse: core.serialization.ObjectSchema<
    serializers.ContextualizedEmbedResponse.Raw,
    VoyageAI.ContextualizedEmbedResponse
> = core.serialization.object({
    object: core.serialization.string().optional(),
    data: core.serialization.list(ContextualizedEmbedResponseDataItem).optional(),
    model: core.serialization.string().optional(),
    usage: ContextualizedEmbedResponseUsage.optional(),
});

export declare namespace ContextualizedEmbedResponse {
    export interface Raw {
        object?: string | null;
        data?: ContextualizedEmbedResponseDataItem.Raw[] | null;
        model?: string | null;
        usage?: ContextualizedEmbedResponseUsage.Raw | null;
    }
}
