// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ContextualizedEmbedRequestInputs: core.serialization.Schema<
    serializers.ContextualizedEmbedRequestInputs.Raw,
    VoyageAI.ContextualizedEmbedRequestInputs
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(core.serialization.list(core.serialization.string())),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace ContextualizedEmbedRequestInputs {
    export type Raw = string[][] | string[];
}
