/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as VoyageAI from "../../api/index";
import * as core from "../../core";
import { ContextualizedEmbedResponseDataItemEmbeddingsItem } from "./ContextualizedEmbedResponseDataItemEmbeddingsItem";

export const ContextualizedEmbedResponseDataItem: core.serialization.ObjectSchema<
    serializers.ContextualizedEmbedResponseDataItem.Raw,
    VoyageAI.ContextualizedEmbedResponseDataItem
> = core.serialization.object({
    embeddings: core.serialization.list(ContextualizedEmbedResponseDataItemEmbeddingsItem).optional(),
    documentIndex: core.serialization.property("document_index", core.serialization.number().optional()),
});

export declare namespace ContextualizedEmbedResponseDataItem {
    interface Raw {
        embeddings?: ContextualizedEmbedResponseDataItemEmbeddingsItem.Raw[] | null;
        document_index?: number | null;
    }
}
