/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as VoyageAI from "../../api/index";
import * as core from "../../core";
import { ContextualizedEmbedResponseResultsItemEmbeddingsItem } from "./ContextualizedEmbedResponseResultsItemEmbeddingsItem";

export const ContextualizedEmbedResponseResultsItem: core.serialization.ObjectSchema<
    serializers.ContextualizedEmbedResponseResultsItem.Raw,
    VoyageAI.ContextualizedEmbedResponseResultsItem
> = core.serialization.object({
    embeddings: core.serialization.list(ContextualizedEmbedResponseResultsItemEmbeddingsItem).optional(),
    documentIndex: core.serialization.property("document_index", core.serialization.number().optional()),
});

export declare namespace ContextualizedEmbedResponseResultsItem {
    interface Raw {
        embeddings?: ContextualizedEmbedResponseResultsItemEmbeddingsItem.Raw[] | null;
        document_index?: number | null;
    }
}
