// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ContextualizedEmbedResponseDataItemDataItem } from "./ContextualizedEmbedResponseDataItemDataItem.js";

export const ContextualizedEmbedResponseDataItem: core.serialization.ObjectSchema<
    serializers.ContextualizedEmbedResponseDataItem.Raw,
    VoyageAI.ContextualizedEmbedResponseDataItem
> = core.serialization.object({
    object: core.serialization.string().optional(),
    data: core.serialization.list(ContextualizedEmbedResponseDataItemDataItem).optional(),
    index: core.serialization.number().optional(),
});

export declare namespace ContextualizedEmbedResponseDataItem {
    export interface Raw {
        object?: string | null;
        data?: ContextualizedEmbedResponseDataItemDataItem.Raw[] | null;
        index?: number | null;
    }
}
