// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EmbedRequestInputType: core.serialization.Schema<
    serializers.EmbedRequestInputType.Raw,
    VoyageAI.EmbedRequestInputType
> = core.serialization.enum_(["query", "document"]);

export declare namespace EmbedRequestInputType {
    export type Raw = "query" | "document";
}
