// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EmbedRequestInput: core.serialization.Schema<
    serializers.EmbedRequestInput.Raw,
    VoyageAI.EmbedRequestInput
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(core.serialization.string()),
]);

export declare namespace EmbedRequestInput {
    export type Raw = string | string[];
}
