// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EmbedResponseUsage: core.serialization.ObjectSchema<
    serializers.EmbedResponseUsage.Raw,
    VoyageAI.EmbedResponseUsage
> = core.serialization.object({
    totalTokens: core.serialization.property("total_tokens", core.serialization.number().optional()),
});

export declare namespace EmbedResponseUsage {
    export interface Raw {
        total_tokens?: number | null;
    }
}
