// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EmbedRequestOutputDtype: core.serialization.Schema<
    serializers.EmbedRequestOutputDtype.Raw,
    VoyageAI.EmbedRequestOutputDtype
> = core.serialization.enum_(["float", "int8", "uint8", "binary", "ubinary"]);

export declare namespace EmbedRequestOutputDtype {
    export type Raw = "float" | "int8" | "uint8" | "binary" | "ubinary";
}
