// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EmbedResponseDataItem } from "./EmbedResponseDataItem.js";
import { EmbedResponseUsage } from "./EmbedResponseUsage.js";

export const EmbedResponse: core.serialization.ObjectSchema<serializers.EmbedResponse.Raw, VoyageAI.EmbedResponse> =
    core.serialization.object({
        object: core.serialization.string().optional(),
        data: core.serialization.list(EmbedResponseDataItem).optional(),
        model: core.serialization.string().optional(),
        usage: EmbedResponseUsage.optional(),
    });

export declare namespace EmbedResponse {
    export interface Raw {
        object?: string | null;
        data?: EmbedResponseDataItem.Raw[] | null;
        model?: string | null;
        usage?: EmbedResponseUsage.Raw | null;
    }
}
