/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as VoyageAI from "../../api/index";
import * as core from "../../core";
import { EmbedResponseDataItem } from "./EmbedResponseDataItem";
import { EmbedResponseUsage } from "./EmbedResponseUsage";

export const EmbedResponse: core.serialization.ObjectSchema<serializers.EmbedResponse.Raw, VoyageAI.EmbedResponse> =
    core.serialization.object({
        object: core.serialization.string().optional(),
        data: core.serialization.list(EmbedResponseDataItem).optional(),
        model: core.serialization.string().optional(),
        usage: EmbedResponseUsage.optional(),
    });

export declare namespace EmbedResponse {
    interface Raw {
        object?: string | null;
        data?: EmbedResponseDataItem.Raw[] | null;
        model?: string | null;
        usage?: EmbedResponseUsage.Raw | null;
    }
}
