/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as VoyageAI from "../../api/index";
import * as core from "../../core";

export const MultimodalEmbedRequestInputType: core.serialization.Schema<
    serializers.MultimodalEmbedRequestInputType.Raw,
    VoyageAI.MultimodalEmbedRequestInputType
> = core.serialization.enum_(["query", "document"]);

export declare namespace MultimodalEmbedRequestInputType {
    type Raw = "query" | "document";
}
