// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MultimodalEmbedResponseDataItem: core.serialization.ObjectSchema<
    serializers.MultimodalEmbedResponseDataItem.Raw,
    VoyageAI.MultimodalEmbedResponseDataItem
> = core.serialization.object({
    object: core.serialization.string().optional(),
    embedding: core.serialization.list(core.serialization.number()).optional(),
    index: core.serialization.number().optional(),
});

export declare namespace MultimodalEmbedResponseDataItem {
    export interface Raw {
        object?: string | null;
        embedding?: number[] | null;
        index?: number | null;
    }
}
