// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MultimodalEmbedRequestInputsItemContentItem } from "./MultimodalEmbedRequestInputsItemContentItem.js";

export const MultimodalEmbedRequestInputsItem: core.serialization.ObjectSchema<
    serializers.MultimodalEmbedRequestInputsItem.Raw,
    VoyageAI.MultimodalEmbedRequestInputsItem
> = core.serialization.object({
    content: core.serialization.list(MultimodalEmbedRequestInputsItemContentItem).optional(),
});

export declare namespace MultimodalEmbedRequestInputsItem {
    export interface Raw {
        content?: MultimodalEmbedRequestInputsItemContentItem.Raw[] | null;
    }
}
