// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MultimodalEmbedRequestEncodingFormat: core.serialization.Schema<
    serializers.MultimodalEmbedRequestEncodingFormat.Raw,
    VoyageAI.MultimodalEmbedRequestEncodingFormat
> = core.serialization.enum_(["base64"]);

export declare namespace MultimodalEmbedRequestEncodingFormat {
    export type Raw = "base64";
}
