// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MultimodalEmbedRequestInputType: core.serialization.Schema<
    serializers.MultimodalEmbedRequestInputType.Raw,
    VoyageAI.MultimodalEmbedRequestInputType
> = core.serialization.enum_(["query", "document"]);

export declare namespace MultimodalEmbedRequestInputType {
    export type Raw = "query" | "document";
}
