// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MultimodalEmbedResponseDataItem } from "./MultimodalEmbedResponseDataItem.js";
import { MultimodalEmbedResponseUsage } from "./MultimodalEmbedResponseUsage.js";

export const MultimodalEmbedResponse: core.serialization.ObjectSchema<
    serializers.MultimodalEmbedResponse.Raw,
    VoyageAI.MultimodalEmbedResponse
> = core.serialization.object({
    object: core.serialization.string().optional(),
    data: core.serialization.list(MultimodalEmbedResponseDataItem).optional(),
    model: core.serialization.string().optional(),
    usage: MultimodalEmbedResponseUsage.optional(),
});

export declare namespace MultimodalEmbedResponse {
    export interface Raw {
        object?: string | null;
        data?: MultimodalEmbedResponseDataItem.Raw[] | null;
        model?: string | null;
        usage?: MultimodalEmbedResponseUsage.Raw | null;
    }
}
