/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Voyage from "../../api/index";
import * as core from "../../core";
import { RerankResponseDataItem } from "./RerankResponseDataItem";
import { RerankResponseUsage } from "./RerankResponseUsage";

export const RerankResponse: core.serialization.ObjectSchema<serializers.RerankResponse.Raw, Voyage.RerankResponse> =
    core.serialization.object({
        object: core.serialization.string().optional(),
        data: core.serialization.list(RerankResponseDataItem).optional(),
        model: core.serialization.string().optional(),
        usage: RerankResponseUsage.optional(),
    });

export declare namespace RerankResponse {
    interface Raw {
        object?: string | null;
        data?: RerankResponseDataItem.Raw[] | null;
        model?: string | null;
        usage?: RerankResponseUsage.Raw | null;
    }
}
