// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const RerankResponseDataItem: core.serialization.ObjectSchema<
    serializers.RerankResponseDataItem.Raw,
    VoyageAI.RerankResponseDataItem
> = core.serialization.object({
    index: core.serialization.number().optional(),
    relevanceScore: core.serialization.property("relevance_score", core.serialization.number().optional()),
    document: core.serialization.string().optional(),
});

export declare namespace RerankResponseDataItem {
    export interface Raw {
        index?: number | null;
        relevance_score?: number | null;
        document?: string | null;
    }
}
