// This file was auto-generated by Fern from our API Definition.

import type * as VoyageAI from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { RerankResponseDataItem } from "./RerankResponseDataItem.js";
import { RerankResponseUsage } from "./RerankResponseUsage.js";

export const RerankResponse: core.serialization.ObjectSchema<serializers.RerankResponse.Raw, VoyageAI.RerankResponse> =
    core.serialization.object({
        object: core.serialization.string().optional(),
        data: core.serialization.list(RerankResponseDataItem).optional(),
        model: core.serialization.string().optional(),
        usage: RerankResponseUsage.optional(),
    });

export declare namespace RerankResponse {
    export interface Raw {
        object?: string | null;
        data?: RerankResponseDataItem.Raw[] | null;
        model?: string | null;
        usage?: RerankResponseUsage.Raw | null;
    }
}
