/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const VoyageAIEnvironment = {
    Default: "https://api.voyageai.com/v1",
} as const;

export type VoyageAIEnvironment = typeof VoyageAIEnvironment.Default;
