/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const VoyageApiEnvironment = {
    Default: "https://api.voyageai.com/v1",
} as const;

export type VoyageApiEnvironment = typeof VoyageApiEnvironment.Default;
