/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const VoyageEnvironment = {
    Default: "https://api.voyageai.com/v1",
} as const;

export type VoyageEnvironment = typeof VoyageEnvironment.Default;
