/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as VoyageApi from "../../../../../api/index";
import * as core from "../../../../../core";

export const RerankerApiRequest: core.serialization.Schema<
    serializers.RerankerApiRequest.Raw,
    VoyageApi.RerankerApiRequest
> = core.serialization.object({
    query: core.serialization.string(),
    documents: core.serialization.list(core.serialization.string()),
    model: core.serialization.string(),
    topK: core.serialization.property("top_k", core.serialization.number().optional()),
    returnDocuments: core.serialization.property("return_documents", core.serialization.boolean().optional()),
    truncation: core.serialization.boolean().optional(),
});

export declare namespace RerankerApiRequest {
    interface Raw {
        query: string;
        documents: string[];
        model: string;
        top_k?: number | null;
        return_documents?: boolean | null;
        truncation?: boolean | null;
    }
}
